### ISSUE TITLE
Doesn't work on mobile versions

### ISSUE THREAD

**Issue by malaguer** [palant/searchlinkfix#104]
I've succesfully installed  Google Search Link Fix in Android 'Kiwi browser' and 'Yandex browser'.

But the extension doesn't work with the mobile versions of Google Search Site. 

If I enable the "desktop version" then the extensions works as expected. 

Could this be fixed to work with mobile versions as well? 

Thanks in advance.

**Comment by palant** [comment]
This is a duplicate of #34.
