### ISSUE TITLE
Add Google Search link fix to Microsoft Edge Addons web store

### ISSUE THREAD

**Issue by MaXfAa** [palant/searchlinkfix#110]
I propose to add the extension to the Microsoft Edge Addons :
https://developer.microsoft.com/en-us/microsoft-edge/extensions/

**Comment by palant** [comment]
I’m winding down this extension. The goal is to release a last version and to deprecate it officially after that. So definitely not going to do this.

**Comment by wickedsp1d3r** [comment]
> I’m winding down this extension. The goal is to release a last version and to deprecate it officially after that. So definitely not going to do this.

Why? I just discovered it and it is working. And now it's coming to its end.
