### ISSUE TITLE
Google images

### ISSUE THREAD

**Issue by peepo** [palant/searchlinkfix#12]
can you do the same for Google Images?

ie where one gets a page of images as the result, each of these is still a google link,

rather than the desired direct link to the image on the site,

that one can copy and paste....

cheers!!!

**Comment by palant** [comment]
There are actually two links there - one leading to the website and another directly to the image. And in fact, they are only one click away - if you left-click the image, a panel will open. This panel has two buttons: "Visit page" and "View image." These are actually links styles as buttons, meaning that they can be copied.

Side-note: That feature isn't working for me if I enter Google Images from the web search. Might only be me, or there is something broken on Google's end.

In general, this extension doesn't change existing links. If a link is already mangled when the page loads (like on Google Images) then it cannot do anything. The purpose is rather preventing websites from messing up links *after* the page loads.

**Comment by peepo** [comment]
you seem to be missing the point. left clicking allows google to track which links I click, 
exactly the same as with text, to quote: " it also helps privacy by preventing the search engines from recording your clicks."

you could offer an option of image or page, I guess page might be more popular as default.

here is an example URL:
http://www.google.co.uk/imgres?imgurl=http%3A%2F%2Fwww.hitechglobal.com%2Fimages%2FPCIe_Plugged.jpg&imgrefurl=http%3A%2F%2Fwww.hitechglobal.com%2Fboards%2Fv5ddr3_pcie.htm&h=435&w=750&tbnid=1DfUAlpCFMJPtM%3A&zoom=1&docid=9eIoZBte8yk08M&ei=9NG0VO3fKIGlUJ3WgEA&tbm=isch&client=ubuntu&ved=0CC8QMygOMA4&iact=rc&uact=3&dur=16108&page=1&start=0&ndsp=25

**Comment by palant** [comment]
I see. However, this extension was never about solving privacy issues on the web - that's way more complicated than fixing links. Some privacy improvements were merely a nice side-effect. Also, Search Link Fix tries hard to avoid changing website functionality - many people certainly consider that panel useful, simply removing it isn't a good option.

As I said, this request is clearly out of scope for Search Link Fix. There is however [this user script](http://userscripts-mirror.org/scripts/show/78355) for example.

**Comment by wesQ3** [comment]
Hi palant, thanks for your work on this extension! Sorry to comment on an old issue. I can open a new one if you prefer, but I think Google's current behavior on image links matches Search Link Fix's mission.

If you click on an image result now and hover over the "View Image" button, the image's location is shown in the status bar, e.g. `https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png`.
But when you click it or copy that link, the URL is rewritten to a google redirect link with extra data attributes embedded in the "View Image" anchor tag e.g.
```
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjK_fymxf_WAhVF4yYKHcjiBmIQjBwIBA&url=https%3A%2F%2Fassets-cdn.github.com%2Fimages%2Fmodules%2Flogos_page%2FGitHub-Mark.png&psig=AOvVaw0KFYo4nvBOOGUwnuXA8PP0&ust=1508600588826267
```

Can you use Search Link Fix's existing link-fixing feature for image results now?
