### ISSUE TITLE
Gmail support

### ISSUE THREAD

**Issue by niko-lay** [palant/searchlinkfix#13]
Возможно сделать тоже самое для ссылок в веб-почте от этих же компаний?

**Comment by palant** [comment]
А можно конкретнее? Gmail ссылки не трогает. Речь о Яндекс.Почта?

Сделать можно что-то лишь в случае, если ссылки меняются при щелчке - если они изначально искажены, то Search Link Fix тут ничем помочь не может.

**Comment by niko-lay** [comment]
Речь про gmail.
Например письмо только что пришло с уведомнением от гитхаба.
Сылка вида <a target="_blank" href="https://github.com/palant/searchlinkfix/issues/13#issuecomment-74091004">view it on GitHub</a>
но при клике происходт редирект вида 
https://mail.google.com/_/scs/mail-static/_/js/k=gmail.main.ru.2eFvJrGYzI8.O/m=m_i,t,it/am=nhEG3f-tP4hxhnbpg75___3uk2J3n5d_96aAZCcA_m_2_wB-D-yjHzI/rt=h/d=1/t=zcms/rs=AHGWq9CTB30_SWb8Q_KtaaO2iw-TeIybSg?fri=b7a6a0d9eb4898309cec5ea89e582d1d

**Comment by palant** [comment]
Действительно, Gmail такое иногда проделывает (почему иногда и какая за этим стоит система - мне пока непонятно). В принципе, Search Link Fix мог бы, наверное, это поведение отключить. Но есть ряд проблем:

* Отладка чего-либо, связанного с Gmail, практически невозможна, там неимоверное количество JavaScript-кода.
* Автоматическое тестирование функциональности Search Link Fix существенно усложнится, поскольку для тестирования требуется аккаунт. С другой стороны, не тестировать нельзя, поскольку там все время что-то меняется.
* Объяснить функционал расширения пользователям станет сложнее - если сейчас это просто "ссылки на страницах поиска", то теперь вдруг добавятся какое-то дополнительные сайты, которые толком и не определишь. Вообще, это явно scope creep - лучше, когда расширение занимается одной конкретной задачей.

Итого вывод: сделать возможно, но лучше не делать, по крайней мере в рамках этого расширения.
