### ISSUE TITLE
Links not cleaned in Yahoo! Search

### ISSUE THREAD

**Issue by dewveil** [palant/searchlinkfix#14]
Hello,
I just downloaded the add-on Google search link fix 1.4.9 on addons.mozilla.org.
I'm using an older Firefox 16 on Windows 7 64-bits, already highly customized.

The links on the results page for Google are all neat and cleaned-up as far as I can see, unfortunately I'm using Yahoo! search (https://search.yahoo.com/) and the results links are still in the form:
http://r.search.yahoo.com/some_garbage_for_tracking_me/another_garbage/http://real_link/some_garbage.

Can anyone confirm that the addon is not working as intended for Yahoo, and maybe help in fixing this?
I'd be really grateful really, it's a really helpful addon!

**Comment by dewveil** [comment]
Hello,
I see that the description of the extension has been updated here on Github to excluse Yahoo! from the description, following the opening of this issue.
Does this mean that the extension cannot be updated to work with Yahoo?
Or does it mean that it will be fixed, but later?

Thanks for any answer...

**Comment by palant** [comment]
I somehow missed this issue being created, sorry.

Yes, Yahoo changed the approach and no longer mangles links on click - the links are rather mangled initially. This means that this extension cannot fix them any more unfortunately.
