### ISSUE TITLE
Prevent mangling of "View Image" on GIS

### ISSUE THREAD

**Issue by Wyatts** [palant/searchlinkfix#16]
In the intermediate panel presented by Google Image Search, it has a link to the actual image, but if you right-click that link to copy it, it gets mangled by their crud.  An example, with image:
![actuallink](https://cloud.githubusercontent.com/assets/400984/6510473/4384463c-c334-11e4-92db-bf06d960eed8.png)

The link pictured, for me, turns into this when I right click:
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0CAQQjBw&url=https%3A%2F%2Fmozorg.cdn.mozilla.net%2Fmedia%2Fimg%2Ffirefox%2Fdesktop%2Findex%2Fanimations%2Ffirefox-logo.bee1d85af18f.png&ei=kpT4VMbwEsyZyATbioDgBg&psig=AFQjCNE5a1C_DNmiJ_0OenrXHKLXqzLvvw&ust=1425663504208213

Using 1.4.9 from https://addons.mozilla.org/

**Comment by palant** [comment]
This seems to have been resolved as a side-effect of https://github.com/palant/searchlinkfix/commit/2ad46155f421eb47fdbdf5ef46259e3bef9e16e9, I've also improved the integration tests for Google Images however so that I'll hopefully notice issues there sooner next time.
