### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Mistress-Anna** [palant/searchlinkfix#17]
I couldn't find the license of this extension, there should be a license.txt or COPYING.txt.
Only the files in lib/ contain a license header, so the license of those doesn't apply to any of the other files (build.py, icons, etc.), that's why there should be a global file (and that would avoid having to dig every file to find a license).

**Comment by palant** [comment]
There is a license header in the individual files but I added LICENSE.txt regardless. The license is MPL 2.0.
