### ISSUE TITLE
Extend to Outbrain

### ISSUE THREAD

**Issue by wbt** [palant/searchlinkfix#18]
For example, in the "You Might Also Like... " section to the right of news articles like [this one](http://abcnews.go.com/International/mh370-probe-man-describes-finding-piece-unravel-missing/story?id=32798981), and many other places where such boxes appear.  While the tracking can serve a valuable purpose in improving the link recommendations, readers should have a choice about data privacy, which is not well respected by Outbrain's policies.

**Comment by palant** [comment]
Sorry but I would rather keep the scope of this extension limited. This is intended to be a very minimal extension, in particular nothing that should be configured. This means that it can only handle the obvious cases, the ones that the extension title already explains - and that's only the search engines.
