### ISSUE TITLE
google replacing almost all urls in search results to their proxy "googleweblight.com"

### ISSUE THREAD

**Issue by 2vek** [palant/searchlinkfix#20]
Apparently, google thinks my internet connection is too slow to open webpages. They are replacing search results to their web proxy. It's happening to most of the searches since yesterday.

more info on their webpage https://support.google.com/webmasters/answer/6211428?hl=en
As their webpage suggest, they are rolling out this feature in selected country. Opting out is only for web owner and not user(as far as I can see on that page).

Here's screenshot of this in action
![screenshot from 2015-09-30 17-06-02](https://cloud.githubusercontent.com/assets/2778313/10191875/a63cf156-6795-11e5-82cc-f4bcd3c86761.png)

I am using Firefox 41 on linux desktop.

**Comment by palant** [comment]
Unfortunately, this is out of scope for this extension. Google search link fix can only prevent links from being mangled, not recover links that are mangled from the start.
