### ISSUE TITLE
[Feature Request] Also repair Mozilla RSS 

### ISSUE THREAD

**Issue by Mannshoch** [palant/searchlinkfix#21]
e.q.
http://news.google.de/news?cf=all&hl=de&pz=1&ned=de&q=austria+-site:.at+-site:.info+-site:.tv&output=rss

This Link gives me an RSS Feed with content I wish. I added it as a RSS into Firefox. But every entry of this Feed point at first to google.

**Comment by palant** [comment]
Unfortunately, that's out of scope for this add-on. Google search link fix doesn't repair any links, it merely prevents them from being mangled.
