### ISSUE TITLE
Describe invisible links

### ISSUE THREAD

**Issue by flyingzebras** [palant/searchlinkfix#22]
Please describe that without this add-on, the crepy Google links users are visiting are not seen in the status bar on mouse hover but when they are clicked on. This is nasty by Google!

Can you please describe this somewhere?

That will make users understand how privacy invading regular web searching really is.

**Comment by palant** [comment]
Frankly, privacy isn't the main goal of this extension. If Google wants to know which links you click on, they still have plenty of opportunities to do that. So I'm not sure whether this aspect should be mentioned - it produces expectations that cannot be fulfilled.

**Comment by Renegarcia1996** [comment]
Look, third party snoopers is what we are as developers, trying to stop.... The issue is clearly not Goolgle, but the cyber cripy freken pirates, we must try to keep at bay or die lost at silicone vulnerable happy valley

**Comment by palant** [comment]
Sure, but this extension isn't equipped for that. Adblock Plus with EasyPrivacy, Ghostery, maybe other extensions I don't know...

**Comment by Renegarcia1996** [comment]
Thanks for your info...it is appreciated!

**Comment by flyingzebras** [comment]
https://github.com/palant/searchlinkfix

>Google search link fix is a Firefox extension that prevents Google and Yandex search pages from modifying search result links when you click them. **This is useful when copying links but it also helps privacy by preventing the search engines from recording your clicks. Detailed description**

I'm happy with that
