### ISSUE TITLE
Extension do not work with noscript

### ISSUE THREAD

**Issue by JonasNo** [palant/searchlinkfix#24]
When noscript disallows script "google.com" your extension do not work which I find strange.

Google is sneaky and slips in tracking scripts. For highest security and privacy it would be good if this extension played nice with security extension noscript..

**Comment by palant** [comment]
This is a known limitation, mentioned in the extension description in fact:

>   This extension cannot recover links after they have been modified. This means that it doesn’t work on Google Search if JavaScript is disabled — Google will produce modified links from the start rather than changing them when you click the link.

**Comment by JonasNo** [comment]
I apologize. Missed that.
Strange that userscripts work, though, but now I'm unsure of that too.

**Comment by palant** [comment]
User scripts that will modify links work, no reason why they shouldn't. This extension doesn't change links however - it merely prevents them from being modified by the webpage.
