### ISSUE TITLE
Add support for Google Shopping

### ISSUE THREAD

**Issue by anonsubmitter** [palant/searchlinkfix#28]
Can you update Google search link fix so that it can remove tracking links from the various regional Google Shopping sites as well?

Sample page: https://www.google.com/shopping/product/7296400249679183478

**Comment by palant** [comment]
No, I cannot, sorry. Google search link fix only makes sure that the original links stay unchanged, it cannot recover original links from URLs that were modified from the start. So it can only work for websites where you see the "real" URL when hovering a link.
