### ISSUE TITLE
It makes some buttons on popup windows un-clickable

### ISSUE THREAD

**Issue by cnzhx** [palant/searchlinkfix#32]
Thanks a lot for this great add-on. Searchlinkfix is very helpful when copying the link from search result page.

I notice that when this add-on is enabled, the buttons on popup window from some webpages become dumb and I **cannot click the button** on the popup window to finish the action. This happens when I use Outlook Web App from my organisation. 

Currently, I found it happens on **Firefox ESR 31.1.1** in Windows 7 and **Firefox 50.0.2** in Linux.

Could you please look into this and make a fix for it?

**Comment by palant** [comment]
Unfortunately, this isn't enough information for me to reproduce this issue. I found an [OWA demo](http://www.mindshiftonline.com/hosted-exchange-demo.xhtml), can you reproduce the issue there? If so, what are the exact steps to go through?

Note that there has been a significant update to Google Search link fix in the meantime, so the new version might not exhibit this behavior any more.

**Comment by cnzhx** [comment]
Hi Wladimir,
Thanks for your concern. The new version fixed the problem.

Thanks a lot for this brilliant add-on :-)
