### ISSUE TITLE
Convert to WebExtension?

### ISSUE THREAD

**Issue by theres-waldo** [palant/searchlinkfix#33]
Mozilla recently announced that starting in Firefox 57, Firefox will no longer support addons that are not WebExtensions.

Are there plans to convert Google search link fix to be a WebExtension, so it can continue working in Firefox 57 and beyond?

**Comment by palant** [comment]
Yes, I plan to do that eventually. This is comparably easy here because the extension stores no data, but I still need to find time for this.
