### ISSUE TITLE
Not working on Mobile version of Google

### ISSUE THREAD

**Issue by designhubby** [palant/searchlinkfix#34]
Are there any plans to make this work for mobile version of Google?

When installed on Firefox Android 50, this plug-in only fixes Desktop View, but not the Mobile View of Google.

I've tested this with Agent set to "Android(Phone)" inside Phony.

**Comment by palant** [comment]
This falls under "known limitations" unfortunately. Just like the no-JS version, the mobile version of Google Search serves mangled links from the start. The original link isn't there in the first place, so this extension cannot do anything about it.

**Comment by jawz101** [comment]
So why does this addon work? https://github.com/Rob--W/dont-track-me-google

**Comment by palant** [comment]
Because that add-on uses a different approach, one that modifies the address presented by the webpage. This isn't something I am willing to do with mine.

**Comment by designhubby** [comment]
What are the risks of that implementation?

**Comment by palant** [comment]
The risk is leaving a website broken if something changes. I don't have a lot of time to put into this extension, so I'd much rather have website changes leave it ineffective than cause a full scale emergency.

**Comment by Marco-Sulla** [comment]
> The risk is leaving a website broken if something changes. I don't have a lot of time to put into this extension, so I'd much rather have website changes leave it ineffective than cause a full scale emergency.

Well, you can check the link with a regexp:

`^\/url\?q=(.*?)\&amp;sa=`

If the regexp has success, `\1` is the real url. If the regexp fails because something changed, the link will remain the same. So I don't see any possible breakage.
