### ISSUE TITLE
regular XML view in Firefox stops working with version 1.6 of SearchLinkFix

### ISSUE THREAD

**Issue by frog23** [palant/searchlinkfix#35]
I noticed a weird issue with the latest version 1.6. When I open any normal XML document without styling information (e.g. http://www.w3schools.com/xml/note.xml ), it opens the regular FF XML View. But once I click anywhere on the document (e.g. when trying to copy the content of an element), all the XML tags disappear and only the content is displayed as regular text. This is really annoying, when one has to work with XML documents a lot. A workaround is to revert back to version 1.5.4 and disable automated updates for this addon. However I guess it would help if this issue would be fixed. Especially for people who are not aware of which addon causes those issues (I had to binary test by disabling/enabling half of all potential addons until I could pin it to this one. I never would have suspected it, the issue occurs on all servers, not just on Google etc. )

Tested in FF 50.1 on Win 7. Also checked with all other addons disabled to avoid emerging issues with other addons.

**Comment by palant** [comment]
Interesting, looks like a Firefox bug. No such behavior in Chrome of course. I'll look into this.
