### ISSUE TITLE
__MSG_name__ instead of proper name

### ISSUE THREAD

**Issue by Tallefer** [palant/searchlinkfix#36]
Firefox 42.0
from addon version 1.6 and forward: name and description is shown as in manifest.json:
  "name": "__MSG_name__",
  "short_name": "__MSG_name__",
  "description": "__MSG_description__"
instead of real text.
Could you please add install.rdf or fix package.json or something?

**Comment by palant** [comment]
I am publishing a WebExtensions build now, Mozilla is no longer allowing anything else. Are you saying that Firefox 42 shows the extension name as MSG_name? This would be a bug in Firefox 42, the extension name in manifest.json is correct (it's a localized name and description). Mind you, WebExtensions bugs in such old Firefox versions are expected, any reason why you don't update?

**Comment by Tallefer** [comment]
Well… so far, it is the only addon in my setup which is acting like that. 
But if you don't want to be bothered with maintaining compatibility, that's ok, I'l just stick install.rdf inside xpi as I did last time. :)

**Comment by palant** [comment]
It's Mozilla who is cutting off backwards compatibility ;). install.rdf isn't part of the WebExtensions format and I'm surprised that it is being respected at all.

**Comment by palant** [comment]
Ok, this is [bug 1192433](https://bugzilla.mozilla.org/show_bug.cgi?id=1192433) - meaning that it's expected to work correctly as of Firefox 45 but not with older versions.
