### ISSUE TITLE
Addon icon doesn't show up anymore

### ISSUE THREAD

**Issue by terr72** [palant/searchlinkfix#37]
Affects Firefox ESR 45.7.0 for Windows and Firefox 50.1.0 for Android.

Steps to reproduce:
Go to the addon list (about:addons).
In Firefox for Windows there's no more addon icon displayed.
In Firefox for Android a broken image icon is being displayed.

**Comment by wasd--** [comment]
Same here, started after the update 1.6.2.

**Comment by palant** [comment]
Thank you for letting me know, turns out the packaging scripts were breaking the icons.
