### ISSUE TITLE
Wikipedia bug on Android

### ISSUE THREAD

**Issue by GuyXY** [palant/searchlinkfix#38]
Whenever I click on a Wikipedia link from Google on my Android device, nothing happens. The site just doesn't load.

**Comment by timofonic** [comment]
Has this been fixed?

**Comment by palant** [comment]
I don't know, but at least I cannot reproduce on the mobile version of Google.

**Comment by palant** [comment]
Doesn't reproduce on Android either for me. I've got Firefox 54 and Google search link fix 1.6.3 on Android 6.0.1. I go to google.com, search for "test", then click the Wikipedia search result. For me it opens in the same tab just fine.

**Comment by palant** [comment]
As we just just established in #40, Google Search is quite different depending on whether you use a smartphone or a tablet. I tried both now but couldn't reproduce this issue. I'm resolving this issue, let me know if you can still reproduce - I'll reopen then. Please provide additional details such as your Firefox and Android version, what device you are using and what you are searching for (meaning: what exact link you click on).
