### ISSUE TITLE
npm warns about deprecated versions (minimatch, graceful-gs) and more....

### ISSUE THREAD

**Issue by timofonic** [palant/searchlinkfix#41]
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN searchlinkfix No repository field.

**Comment by palant** [comment]
That's not our immediate dependencies, I think they are being used by gulp. These are merely development dependencies so not a real concern. Eventually gulp will manage to update.
