### ISSUE TITLE
Not sure if working on Opera...

### ISSUE THREAD

**Issue by ZenFi** [palant/searchlinkfix#42]
Hey and thank you for making this extension.

I'm not sure if this works on Opera... Yandex Images I tried and at least there no direct links were given.

Could you look into?

**Comment by palant** [comment]
Yes, it is definitely working in Opera - tested with Google and Yandex text search. Yandex Images is complicated however, most of the links are mangled from the start. This extension cannot recover mangled links, it will merely prevent links from being mangled when you click them. It seems that no such mangling on the fly is being performed for Yandex Images.

**Comment by ZenFi** [comment]
Hmm OK I might look into it later.
