### ISSUE TITLE
Minimal Opera version

### ISSUE THREAD

**Issue by ZenFi** [palant/searchlinkfix#43]
Mini version(s)?

Opera can handle this just fine :D

**Comment by palant** [comment]
Could you explain yourself a bit better? I have no idea what you are asking about.

**Comment by palant** [comment]
Oh, are you asking for Opera Mini support? I have no idea, Opera Mini seems to expect the same extension packages. Can't you install the extension there right now? Or is it merely broken?

**Comment by ZenFi** [comment]
No not OPR Mini. I was referring to the forks.. There seems to be some downsized version for Opera?

**Comment by palant** [comment]
Now you lost me again. The version for Opera is exactly the same as the one for Chrome and Firefox. What exactly are you asking about?

**Comment by ZenFi** [comment]
ok! there was just talk of opera minimal or something in some of the branches/forks.

**Comment by palant** [comment]
What branches? What forks?

**Comment by ZenFi** [comment]
Ok I might have misunderstood, but yeah,,

this I was referring to https://github.com/palant/searchlinkfix/commit/c30d0c1a97bdfb87682fa6359df776b8faa40428

**Comment by palant** [comment]
Opera 35 and older is not supported, so the extension should not install there. That's because some newer JavaScript syntax such as destructuring assignments won't work in this version. So Google search link fix would be broken in this Opera version if it installed.

**Comment by ZenFi** [comment]
35 is dead old anyway. I dunno why it's so important to keep XP supported anyway..
