### ISSUE TITLE
URL scope

### ISSUE THREAD

**Issue by vaindil** [palant/searchlinkfix#44]
Hello! Thanks for this extension.

Is it necessary to run the extension on all URLs? Wouldn't it be enough to run only on the specific domains supported in content.js? I know this would be a bit more annoying to manage, but IMO it's better than Chrome showing that the extension can "Read and change all your data on the websites that you visit". I'm happy to submit a quick PR if you'd like.

**Comment by ZenFi** [comment]
Opera for me shows about this extensions permissions: none 
How come? I know it cleans up urls though..

Manage? Is there settings page as well? According to Opera that would be no...

**Comment by palant** [comment]
Do you have a good way to pull a list of all Google domains? Something we could repeat occasionally because that list changes, so ideally even automatically.

**Comment by palant** [comment]
I found https://www.google.com/supported_domains which is apparently exactly what is needed here.

**Comment by palant** [comment]
This will be part of version 1.6.4, to be released shortly.

**Comment by palant** [comment]
For reference, this change has been partially reverted for Firefox in version 1.6.5. See https://palant.de/2017/08/05/revisiting-permission-prompt-for-firefox-extensions for an explanation.
