### ISSUE TITLE
Do not work in yandex

### ISSUE THREAD

**Issue by svoa** [palant/searchlinkfix#49]
Do not work in yandex at least in Firefox 56.
You can check it out for yourself,  for example https://yandex.ru/yandsearch?clid=2186618&text=example&lr=213 copy any link from this page and paste it in address bar "you get some gibberish instead of what you wanted" like said in description of addon.

**Comment by GauriSpears** [comment]
I confirm the issue on Firefox 56.0.1. Fixing of yandex links is broken, google links are OK.

**Comment by qsoMaster** [comment]
Help . Do not work in yandex . Firefox 52.4.0 esr , Firefox  56.0.2 . SRWare iron 53.0.2800.0

**Comment by palant** [comment]
Unfortunately, the issue here is a Web Extensions limitation - the extension cannot register an event handler that is guaranteed to run after the one registered by the page. I found a solution that mostly of works in Firefox, in Chrome it doesn't.

**Comment by palant** [comment]
Yandex-specific hack it is... New version coming up shortly.
