### ISSUE TITLE
Reqest: Could this be extended to support gmail links as well?

### ISSUE THREAD

**Issue by rasmushandersen** [palant/searchlinkfix#54]
I observe similar behaviour when clicking links on gmail. I am happy to assist with the implementation, but i would need some pointers on where and how to get started.

**Comment by palant** [comment]
It should be easy to remove the redirect on GMail links. However, I would advise against it. The intermediate page makes sure that no private data leaks via the referrer header, it's a common security mechanism for webmail clients.
