### ISSUE TITLE
Installed, but still seeing redirect tracking link

### ISSUE THREAD

**Issue by 9jkh** [palant/searchlinkfix#58]
Thought it was supposed to scrub this (FF 57.0.3). Am I misunderstanding how it's supposed to work?

[url=https://postimages.org/][img]https://s13.postimg.org/vpgz9c54n/Screen_Shot_2018-01-02_at_2.31.44_PM.png[/img][/url]

**Comment by palant** [comment]
This works fine for me, maybe you could give me some more details? Did you disable JavaScript by any chance? If you did, that's a known limitation - this extension cannot "scrub" links, it can only prevent correct links from being mangled when clicked.

If that's not the issue, maybe you I could give me some details. In particular, the full URL of your search would be good. Also, I take it that you are in UK and right-clicked the last result on that page, which made the mangled link appear?

**Comment by 9jkh** [comment]
Thanks for the quick reply. Yep, that was it, JS was not enabled for Google. Using the new version of NoScript for 57+ and wasn't paying attention; didn't realize that Google wasn't allowed. searchlinkfix does indeed work. With searchlinkfix temporarily disabled and Google allowed, the redirect tracking link appears on mousedown. With searchlinkfix enabled, it stays clean on mousedown. (NoScript pre-57 sanitizes the redirect link, but no longer does with versions for 57.) 

Thanks for this extension. Btw, not in UK, just selected something at random from a search using "123."

**Comment by palant** [comment]
Thank you for confirming, good to know that the issue isn't on my end.
