### ISSUE TITLE
In Google search result page, links are clean without your extension

### ISSUE THREAD

**Issue by dehghani-mehdi** [palant/searchlinkfix#59]
Hi,

I used searchlinkfix  and I like that. thanks.

But seems Google changes something, now links are clean without your extension.

![screenshot_1](https://user-images.githubusercontent.com/9152330/35961449-fe9e2656-0cc2-11e8-85e9-fd2884e72e2d.png)

**Comment by palant** [comment]
Links on Google are always clean when you merely hover them. They are merely replaced by the obfuscated version when you click them (this includes right-click, e.g. when copying). That's what this extension is meant to address. Don't you see this behavior any more?

**Comment by dehghani-mehdi** [comment]
With your extension the copied link is clean. seems link wrong issue. I'm sorry.
Thanks.
