### ISSUE TITLE
Google search results aren't parsed in mobile

### ISSUE THREAD

**Issue by Zcehtro** [palant/searchlinkfix#62]
I just installed the add-on in Firefox for Android and the links aren't fixed.

I supposed that the problem was that it only worked in the desktop version. So I activated the "Request desktop site" option and voila: all the links were fixed correctly as expected.

Please make this add-on compatible with mobile sites. Thanks.

**Comment by palant** [comment]
This is a duplicate of #34, listed under "known limitations."
