### ISSUE TITLE
Firefox: Does not work when JS is disabled for google.com domain

### ISSUE THREAD

**Issue by cookiengineer** [palant/searchlinkfix#68]
If I use e.g. uMatrix to disable JS for the `google.com` domain, I successfully land in the oldskool google results page that loads faster when being on EDGE / 3G or other slow wireless connections.

However, the `searchlinkfix` extension does not rewrite the URLs then. I uploaded the HTML my firefox receives (no DOM modifications) here, in case the HTML changes per country or it's hard to reproduce: https://gist.github.com/cookiengineer/f4e8710b35c3f8529432408f3a7cff78

Steps to reproduce:

1. Use Firefox and latest uBlock Origin + uMatrix + searchlinkfix extension
2. go to google.com, in uMatrix disable JS for `www.google.com` (3 from top, 5 from left)
3. go to google.com again and search something
4. on the results page, the result items now contain the `google.com/url?...` links again

**Comment by cookiengineer** [comment]
I think the code that fails in that case is here, as `window.google` obviously isn't set in that case: https://github.com/palant/searchlinkfix/blob/master/data/content.js#L75

Maybe there should be an additional logic, comparing the domain and whether or not location.href starts with `/search` or so instead?

**Comment by palant** [comment]
From "Known limitations":

* This extension cannot recover links after they have been modified. This means that it doesn’t work on Google Search on smartphones (tablet version will work fine) or if JavaScript is disabled — Google will produce modified links from the start rather than changing them when you click the link.
