### ISSUE TITLE
Middle mouse button click on links does nothing on old Firefoxes

### ISSUE THREAD

**Issue by VisualKei** [palant/searchlinkfix#7]
Happened to stumble upon this issue with v1.4.6 on a machine with Firefox 20. It works normally in ESR24 though.
Don't know is this an issue for you, but since you're declaring compatibility starting with FF16 - it may be.

**Comment by palant** [comment]
I ported Google search link fix back to the Add-on SDK - side-effect is that anything before Firefox 38 is no longer supported.
