### ISSUE TITLE
Unrecognized manifest key

### ISSUE THREAD

**Issue by smed79** [palant/searchlinkfix#72]
Google search link fix 1.6.7
Chromium 70.0.3538.77 (Build officiel) Arch Linux (64 bits)

error that occurs all the time

```
Unrecognized manifest key 'minimum_opera_version'
"minimum_opera_version": "36.0",
```
screenshot
![warnings](https://user-images.githubusercontent.com/1873139/47887898-2ccfb480-de5b-11e8-88ae-55c1e59e5618.png)

Thank you.

**Comment by palant** [comment]
That's merely a warning, not an error. And it's a warning that I have to accept in order to have the same build work in both Chrome and Opera. With the Web Extensions standardization effort being stuck, that's as good as we can get...
