### ISSUE TITLE
Signed version in the making?

### ISSUE THREAD

**Issue by bachlipp** [palant/searchlinkfix#78]
Hi,
I was really happy with this add on, especially it did a great job without even noticing that it was there. Sadly, since Mozilla forces add ons to be signed, Firefox disabled this plugin. Of course, there are workarounds like resorting to a Firefox Extended Support Release with special configuration, but it was really great if you could provide a signed update to your add on.
Cheers
Philipp

**Comment by palant** [comment]
See https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/ - this is a Firefox issue, not ours. I guess that you've been offline for a while?

**Comment by bachlipp** [comment]
Hi Wladimir,
thank you very much! Yes, now this works for me, too.
Cheers
Philipp
