### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by filips123** [palant/searchlinkfix#83]
Based on README, this still required Python 2.7 for integration tests. You should update this to Python 3 as Python 2 will have EOL in less than 2 months (1 January 2020).

**Comment by palant** [comment]
The issue here is the dependency on [marionette-driver](https://pypi.org/project/marionette-driver/). Judging by [bug 1355537](https://bugzilla.mozilla.org/show_bug.cgi?id=1355537), Python 3 support here still isn't ready, even though there is hope that it will be added soon.

**Comment by palant** [comment]
Not that the integration tests work at all right now. The add-on used to collect URLs visited is not compatible with current Firefox versions.

**Comment by palant** [comment]
It seems that #84 is the best way forward here.
