### ISSUE TITLE
Switch integration tests to Puppeteer

### ISSUE THREAD

**Issue by palant** [palant/searchlinkfix#84]
Integration tests are broken right now because the extension used to collect network requests is incompatible with current Firefox. It's also an unnecessarily complicated solution, it being based on Mozilla's Python-based marionette driver.

It seems that using headless Chrome will be far easier, probably via Puppeteer. An unpacked extension can be loaded with the `--load-extension` command line flag, network requests are directly available via remote debugging API.

**Comment by filips123** [comment]
I think k that you should test both with Chrome and Firefox. Note that Puppeteer has also experiment Firefox support.

**Comment by palant** [comment]
I think that I should first get the tests running and executed at all. As you can probably tell from them being broken, they haven't been run in a long time. Main reason is websites changing regularly and breaking tests - always in ways that don't affect extension functionality. So it's considerable effort to maintain these tests but very little gain so far.

**Comment by palant** [comment]
I mostly got Google Search integration test converted. This works well, but the page is really complex. For example, the URL mangling is disabled in current Chrome versions (based on user agent, expects ping support) and expects a preceding `mouseover` event. I'm afraid that we again are going to see more changes here that will break the tests without affecting extension functionality.

**Comment by palant** [comment]
For reference, Chrome cannot be run in headless mode due to https://bugs.chromium.org/p/chromium/issues/detail?id=706008. Adapting the title accordingly.

**Comment by palant** [comment]
As far as I'm concerned, this is resolved. Running integration tests via Travis CI doesn't work unfortunately because headless Chrome won't allow extensions, yet Travis CI can only run it headless.

Feel free to experiment with Puppeteer-Firefox if you like, but I expect it to be difficult because Firefox doesn't allow extensions to be specified on the command line.
