### ISSUE TITLE
Doesn't work on zoomed images in Google Image Search

### ISSUE THREAD

**Issue by sinni800** [palant/searchlinkfix#85]
Copying the link at the following spot in the Google Image Search still results in a google.com/url link

![firefox_2019-11-06_21-10-59](https://user-images.githubusercontent.com/2879097/68334003-fd8cfc80-00d9-11ea-9c25-20059d61b5f3.jpg)

**Comment by palant** [comment]
Yes, this link is mangled from the start - there is no unmangled link to be protected here. So this extension cannot do its job.

**Comment by sinni800** [comment]
Wouldn't it be possible take the mangled link and extract the url out of it: 
```
var mangled_link = "https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FText_nailing&psig=AOvVaw22PvIeX1Dlbn5x_R44BkJw&ust=1573739617001302";

var url = mangled_link.match(/url=([^&]*)/)[1];
url = decodeURIComponent(url);
```
url will contain `https://en.wikipedia.org/wiki/Text_nailing` at this point

I know there is no guarantee this behaviour will stay, but it has been like this for a long time at least.

**Comment by palant** [comment]
Yes, in principle it would work. However, this approach is out of scope - there is only so much time that I can put into maintaining this extension, I cannot deal with emergencies because of Google search link fix breaking website functionality due to assumptions that are no longer true.

**Comment by sinni800** [comment]
I see, that's a good point.
