### ISSUE TITLE
searchlinkfix icon disappears in the add-on's manager tab

### ISSUE THREAD

**Issue by ediowar** [palant/searchlinkfix#90]
If the add-on's manager tab is refreshed in offline mode or if the internet connection is not available.

**Comment by palant** [comment]
Presumably that's Firefox. Which Firefox version and what operating system? I cannot reproduce this in Firefox 77 on Linux, and I don't really see why this would happen.

**Comment by ediowar** [comment]
Firefox 77, Ubuntu 16.04.6 LTS
Image Location https://addons.cdn.mozilla.net/user-media/addon_icons/351/351740-32.png?modified=mcrushed
https://github.com/uBlockOrigin/uBlock-issues/issues/939

**Comment by palant** [comment]
Added 32x32 icon, not sure when Firefox started to use this one.

**Comment by ediowar** [comment]
Fixed/

**Comment by ediowar** [comment]
Fixed.
