### ISSUE TITLE
Tamper-/greasmonkey script?

### ISSUE THREAD

**Issue by psonnosp** [palant/searchlinkfix#94]
First of thanks for a very useful add on.

Would it be possible to convert it into a script or into a version compatible with Pale Moon that doesn't support webextensions so I can make use of it there too?

**Comment by palant** [comment]
Yes, you can use the content script without any changes: https://github.com/palant/searchlinkfix/blob/master/data/content.js

In principle it can run on every site. If you want it to run on specific websites only, the list can be seen under https://github.com/palant/searchlinkfix/blob/master/manifest.json#L24 plus all the domains from https://www.google.com/supported_domains.

**Comment by psonnosp** [comment]
Nice, thanks a lot!
